# action.yml
name: Netling
description: Run performance tests using Netling
author: NaveenKumar Namachivayam - https://qainsights.com

branding:
  color: blue
  icon: zap

inputs:
  url:
    required: true
    description: url to test
  threads:
    required: true
    description: number of threads to inject
  duration:
    required: true
    description: duration of your test
  
runs:
  using: 'docker'
  image: 'docker://qainsights/netling'
  args:
  - "${{ inputs.url }}"
  - "-t"
  - "${{ inputs.threads }}"
  - "-d"
  - "${{ inputs.duration }}"
