on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Netling Tests
        uses: ./
        with:
          url: "https://example.com"
          threads: "1"
          duration: "10"
